
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.tconstruct]
				ender_slime = true
				fancy_item_frame = true
				sky_slime = true

			[light_sources.settings.entities.minecraft]
				axolotl = true
				zoglin = true
				allay = true
				llama = true
				bat = true
				husk = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				drowned = true
				item = true
				horse = true
				vindicator = true
				minecart = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				ocelot = true
				item_frame = true
				phantom = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				polar_bear = true
				painting = true
				wither = true

			[light_sources.settings.entities.splendid_slimes]
				splendid_slime = true

			[light_sources.settings.entities.enigmaticgraves]
				grave = true

			[light_sources.settings.entities.immersiveengineering]
				commando = true
				railgun_shot = true
				fusilier = true
				chemthrower_shot = true
				bulwark = true
				revolver_shot = true

			[light_sources.settings.entities.alexsmobs]
				devils_hole_pupfish = true
				pollen_ball = true
				murmur_head = true
				kangaroo = true
				blue_jay = true
				skelewag = true
				bone_serpent_part = true
				cachalot_echo = true
				catfish = true
				laviathan = true
				anteater = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				endergrade = true
				jerboa = true
				mungus = true
				skunk = true
				dropbear = true
				bunfungus = true
				roadrunner = true
				rattlesnake = true
				leafcutter_ant = true
				blobfish = true
				lobster = true
				mimicube = true
				grizzly_bear = true
				snow_leopard = true
				farseer = true
				potoo = true
				tiger = true
				rocky_roller = true
				centipede_head = true
				flutter = true
				orca = true
				rain_frog = true
				maned_wolf = true
				crow = true
				elephant = true
				cosmaw = true
				crocodile = true
				stradpole = true
				crimson_mosquito = true
				spectre = true
				sand_shot = true
				seal = true
				hammerhead_shark = true
				sunbird = true
				straddler = true
				emu = true
				triops = true
				mimic_octopus = true
				gazelle = true
				soul_vulture = true
				tarantula_hawk = true
				guster = true
				underminer = true
				enderiophage = true
				terrapin = true
				gorilla = true
				flying_fish = true
				platypus = true
				capuchin_monkey = true
				murmur = true
				cockroach = true
				komodo_dragon = true
				bone_serpent = true
				centipede_body = true
				seagull = true
				mantis_shrimp = true
				raccoon = true
				fly = true
				giant_squid = true
				toucan = true
				cachalot_whale = true
				skreecher = true
				hummingbird = true
				frilled_shark = true
				bison = true
				warped_toad = true
				sugar_glider = true

			[light_sources.settings.entities.eidolon]
				giant_skeleton = true
				wraith = true
				slimy_slug = true
				raven = true
				chant_caster = true
				necromancer = true
				zombie_brute = true

			[light_sources.settings.entities.hexical]
				animated_scroll = true

			[light_sources.settings.entities.aether]
				slider = true
				sun_spirit = true
				zephyr = true
				flying_cow = true
				whirlwind = true
				poison_needle = true
				mimic = true
				thunder_crystal = true
				valkyrie_queen = true
				sentry = true
				cockatrice = true
				hammer_projectile = true
				golden_swet = true
				fire_crystal = true
				fire_minion = true
				evil_whirlwind = true
				golden_parachute = true
				blue_swet = true
				cloud_minion = true
				valkyrie = true
				phyg = true
				aerbunny = true
				lightning_knife = true
				sheepuff = true
				aerwhale = true
				ice_crystal = true
				cold_parachute = true
				aechor_plant = true
				moa = true
				cloud_crystal = true

			[light_sources.settings.entities.biomeswevegone]
				oddion = true
				man_o_war = true

			[light_sources.settings.entities.botania]
				mana_burst = true

			[light_sources.settings.entities.create_mobile_packages]
				robo_bee = true

			[light_sources.settings.entities.sushigocrafting]
				tuna = true
				shrimp = true

			[light_sources.settings.entities.atmospheric]
				tetra = true
				cochineal = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true

			[light_sources.settings.entities.upgrade_aquatic]
				thrasher = true
				lionfish = true
				nautilus = true

			[light_sources.settings.entities.thermal]
				blitz = true
				blizz = true
				blitz_projectile = true
				basalz = true

			[light_sources.settings.entities.quark]
				wraith = true
				shiba = true
				forgotten = true
				toretoise = true
				glass_frame = true
				stoneling = true
				foxhound = true
				crab = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true
				gantry_contraption = true

			[light_sources.settings.entities.essentials]
				cannon_skull = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				ice_cube = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.ars_elemental]
				siren_entity = true

			[light_sources.settings.entities.irons_spellbooks]
				pyromancer = true
				citadel_keeper = true
				necromancer = true
				archevoker = true
				fire_breath = true
				firebolt = true
				summoned_skeleton = true
				priest = true
				fire_field = true
				dead_king_corpse = true
				summoned_zombie = true
				magic_missile = true
				magma_ball = true
				guiding_bolt = true
				firefly_swarm = true
				root = true
				cryomancer = true
				healing_aoe = true
				icicle = true
				gust = true

			[light_sources.settings.entities.powah]
				charged_snowball = true

			[light_sources.settings.entities.environmental]
				deer = true
				zebra = true
				reindeer = true
				koi = true
				duck = true
				tapir = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.pneumaticcraft]
				logistics_frame_default_storage = true
				logistics_drone = true
				logistics_frame_storage = true
				heat_frame = true
				logistics_frame_requester = true
				logistics_frame_passive_provider = true
				logistics_frame_active_provider = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.endergetic]
				booflo_baby = true
				poise_cluster = true
				booflo = true
				booflo_adolescent = true
				puff_bug = true

			[light_sources.settings.entities.lost_aether_content]
				cloud_shot = true
				aerwhale_king = true
				falling_rock = true

			[light_sources.settings.entities.embers]
				ember_projectile = true
				ancient_golem = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.aquaculture]
				tuna = true
				jellyfish = true
				bluegill = true
				muskellunge = true
				brown_shrooma = true
				catfish = true
				tambaqui = true
				rainbow_trout = true
				boulti = true
				starshell_turtle = true
				gar = true
				perch = true
				capitaine = true
				arrau_turtle = true
				atlantic_halibut = true
				piranha = true
				red_grouper = true
				arapaima = true
				box_turtle = true
				atlantic_herring = true
				bayad = true
				carp = true
				red_shrooma = true
				brown_trout = true
				synodontis = true
				smallmouth_bass = true
				minnow = true

			[light_sources.settings.entities.undergarden]
				stoneborn = true
				rotwalker = true
				mog = true
				gloomper = true
				rotling = true
				sploogie = true
				rotbeast = true
				smog_mog = true
				brute = true
				nargoyle = true
				blisterbomb = true
				muncher = true
				forgotten = true
				gwib = true
				gwibling = true
				dweller = true
				forgotten_guardian = true
				scintling = true

			[light_sources.settings.entities.ars_nouveau]
				wilden_guardian = true
				wilden_hunter = true
				follow_proj = true
				starbuncle = true
				gift_starby = true
				flying_item = true
				flourishing_weald_walker = true
				bookwyrm = true
				drygmy = true
				summon_wolf = true
				whirlisprig = true

			[light_sources.settings.entities.hexcasting]
				wall_scroll = true

			[light_sources.settings.entities.species]
				cliff_hanger = true
				spectre = true
				treeper = true
				wicked_fireball = true
				birt = true
				limpet = true
				leaf_hanger = true
				bewereager = true
				wraptor = true
				quake = true
				ghoul = true
				deepfish = true
				wicked = true

			[light_sources.settings.entities.deep_aether]
				gentle_wind = true
				eots_segment = true
				wind_crystal = true
				eots_controller = true
				baby_zephyr = true
				venomite_bubble = true
				aerglow_fish = true
				venomite = true
				quail = true

			[light_sources.settings.entities.aether_redux]
				mykapod = true
				vanilla_swet = true
				shimmercow = true
				blightbunny_spawner = true
				blightbunny = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true

			[light_sources.settings.entities.mythicbotany]
				alf_pixie = true

